name: "Continuous integration"

on:
  pull_request:
    branch: ["main"]
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - run: |
          pip install -e .[testing]
          pytest -vv
